import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import { UserProvider } from '@/lib/user-provider';
import { getSession } from '@/lib/session';
import { AuthToggle } from '@/components/auth-toggle';
import { SidebarProvider, SidebarTrigger, SidebarInset } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
import { ThemeProvider } from '@/components/theme-provider';
import { ModeToggle } from '@/components/app-mode-toggle';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getSession();
	const isLoggedIn = !!session?.userId;
	const isAuthenticated = session?.userType === 'authenticated';

	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
				<UserProvider userId={session?.userId} userType={session?.userType}>
					<ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
						{isAuthenticated ? (
							<SidebarProvider>
								<AppSidebar />
								<SidebarInset>
									<div className="m-4">
										<header className="flex justify-between items-center">
											<SidebarTrigger />
											<div className="flex justify-between items-center gap-4">
												<AuthToggle isLoggedIn={isLoggedIn} />
												<ModeToggle />
											</div>
										</header>
										<main>{children}</main>
									</div>
								</SidebarInset>
							</SidebarProvider>
						) : (
							<div className="m-4">
								<header className="flex justify-between items-center">
									<div></div>
									<div className="flex justify-between items-center gap-4">
										<AuthToggle isLoggedIn={isLoggedIn} />
										<ModeToggle />
									</div>
								</header>
								<main>{children}</main>
							</div>
						)}
						<Toaster />
					</ThemeProvider>
				</UserProvider>
			</body>
		</html>
	);
}
